/var/spool/slurmd/job11597/slurm_script: line 10: /data/[username]/anaconda3/etc/profile.d/conda.sh: No such file or directory
[I 2024-08-25 03:31:17.644 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-08-25 03:31:17.650 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2024-08-25 03:31:17.653 ServerApp] jupyterlab | error linking extension: Trait, kernel_name, not found.
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 346, in link_extension
        extension.link_all_points(self.serverapp)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 228, in link_all_points
        self.link_point(point_name, serverapp)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 218, in link_point
        point.link(serverapp)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 140, in link
        linker(serverapp)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 404, in _link_jupyter_server_extension
        self.update_config(self.serverapp.config)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/notebook_shim/shim.py", line 141, in update_config
        shimmed_config = self.shim_config_from_notebook_to_jupyter_server(
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/notebook_shim/shim.py", line 232, in shim_config_from_notebook_to_jupyter_server
        raise TraitError("Trait, {}, not found.".format(trait_name))
    traitlets.traitlets.TraitError: Trait, kernel_name, not found.
[I 2024-08-25 03:31:17.662 ServerApp] notebook | extension was successfully linked.
[I 2024-08-25 03:31:18.266 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-08-25 03:31:18.323 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-08-25 03:31:18.326 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-08-25 03:31:18.330 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-08-25 03:31:18.344 LabApp] JupyterLab extension loaded from /data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyterlab
[I 2024-08-25 03:31:18.344 LabApp] JupyterLab application directory is /data/tianyu_guo/miniconda3/envs/nanogpt/share/jupyter/lab
[I 2024-08-25 03:31:18.346 LabApp] Extension Manager is 'pypi'.
[I 2024-08-25 03:31:18.367 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-08-25 03:31:18.383 ServerApp] notebook | extension was successfully loaded.
[I 2024-08-25 03:31:18.383 ServerApp] Serving notebooks from local directory: /data/tianyu_guo/birth
[I 2024-08-25 03:31:18.383 ServerApp] Jupyter Server 2.14.0 is running at:
[I 2024-08-25 03:31:18.383 ServerApp] http://compute-permanent-node-535:8888/tree?token=28a5d9f2154ea379ef82cccb9bab7d61fbdfdc4d94058b88
[I 2024-08-25 03:31:18.383 ServerApp]     http://127.0.0.1:8888/tree?token=28a5d9f2154ea379ef82cccb9bab7d61fbdfdc4d94058b88
[I 2024-08-25 03:31:18.383 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-08-25 03:31:18.389 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///data/tianyu_guo/.local/share/jupyter/runtime/jpserver-982672-open.html
    Or copy and paste one of these URLs:
        http://compute-permanent-node-535:8888/tree?token=28a5d9f2154ea379ef82cccb9bab7d61fbdfdc4d94058b88
        http://127.0.0.1:8888/tree?token=28a5d9f2154ea379ef82cccb9bab7d61fbdfdc4d94058b88
[I 2024-08-25 03:31:18.518 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-08-25 03:31:59.462 ServerApp] 404 GET /hub/api (@10.0.0.99) 23.33ms referer=None
[I 2024-08-25 03:31:59.466 ServerApp] 302 GET / (@10.0.0.99) 0.42ms
[I 2024-08-25 03:31:59.468 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.32ms
[W 2024-08-25 03:32:01.149 ServerApp] 404 GET /hub/api (@10.0.0.99) 3.61ms referer=None
[I 2024-08-25 03:32:01.150 ServerApp] 302 GET / (@10.0.0.99) 0.22ms
[I 2024-08-25 03:32:01.153 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.28ms
[W 2024-08-25 03:32:02.960 ServerApp] 404 GET /hub/api (@10.0.0.99) 4.19ms referer=None
[I 2024-08-25 03:32:02.963 ServerApp] 302 GET / (@10.0.0.99) 0.19ms
[I 2024-08-25 03:32:02.965 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.29ms
[I 2024-08-25 03:32:03.030 ServerApp] Kernel started: 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[I 2024-08-25 03:32:03.913 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[W 2024-08-25 03:32:10.041 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 2.26ms referer=None
[W 2024-08-25 03:32:10.041 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 2.94ms referer=None
[W 2024-08-25 03:32:10.042 ServerApp] 404 GET /hub/api (@10.0.0.99) 3.52ms referer=None
[W 2024-08-25 03:32:10.043 ServerApp] 404 GET /hub/api (@10.0.0.99) 4.09ms referer=None
[I 2024-08-25 03:32:10.044 ServerApp] 302 GET / (@10.0.0.99) 0.22ms
[I 2024-08-25 03:32:10.046 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.31ms
[W 2024-08-25 03:32:10.050 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 0.56ms referer=None
[W 2024-08-25 03:32:10.051 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 0.57ms referer=None
[W 2024-08-25 06:14:23.878 ServerApp] 404 GET /hub/api (@10.0.0.99) 4.21ms referer=None
[I 2024-08-25 06:14:28.492 ServerApp] 302 GET / (@10.0.0.99) 0.36ms
[I 2024-08-25 06:14:28.568 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.50ms
[W 2024-08-25 06:14:28.946 ServerApp] 404 GET /hub/api (@10.0.0.99) 1.37ms referer=None
[I 2024-08-25 06:14:28.948 ServerApp] 302 GET / (@10.0.0.99) 0.20ms
[I 2024-08-25 06:14:28.951 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.26ms
[I 2024-08-25 06:14:28.974 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[W 2024-08-25 06:14:33.713 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 2.45ms referer=None
[W 2024-08-25 06:14:33.714 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 0.64ms referer=None
[W 2024-08-25 06:14:33.715 ServerApp] 404 GET /hub/api (@10.0.0.99) 0.68ms referer=None
[W 2024-08-25 06:14:33.715 ServerApp] 404 GET /hub/api (@10.0.0.99) 0.58ms referer=None
[I 2024-08-25 06:14:34.164 ServerApp] 302 GET / (@10.0.0.99) 0.27ms
[I 2024-08-25 06:14:34.193 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.33ms
[W 2024-08-25 06:14:34.205 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 0.75ms referer=None
[W 2024-08-25 06:14:34.215 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 0.66ms referer=None
[I 2024-08-25 13:32:21.876 ServerApp] Starting buffering for 6b0485a9-18db-479b-bd8d-5b53ea62ebce:24889f47-7578-4d98-84fa-21fdf3ec5ee2
[W 2024-08-25 17:32:00.194 ServerApp] 404 GET /hub/api (@10.0.0.99) 4.00ms referer=None
[I 2024-08-25 17:32:05.239 ServerApp] 302 GET / (@10.0.0.99) 0.43ms
[I 2024-08-25 17:32:05.294 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.50ms
[W 2024-08-25 17:32:05.492 ServerApp] 404 GET /hub/api (@10.0.0.99) 1.51ms referer=None
[I 2024-08-25 17:32:05.494 ServerApp] 302 GET / (@10.0.0.99) 0.19ms
[I 2024-08-25 17:32:05.496 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.27ms
[I 2024-08-25 17:32:05.519 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[W 2024-08-25 17:32:10.657 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 3.24ms referer=None
[W 2024-08-25 17:32:10.657 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 3.55ms referer=None
[W 2024-08-25 17:32:10.658 ServerApp] 404 GET /hub/api (@10.0.0.99) 3.85ms referer=None
[W 2024-08-25 17:32:10.658 ServerApp] 404 GET /hub/api (@10.0.0.99) 4.14ms referer=None
[I 2024-08-25 17:32:10.711 ServerApp] 302 GET / (@10.0.0.99) 0.33ms
[I 2024-08-25 17:32:15.729 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.61ms
[W 2024-08-25 17:32:15.740 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 1.02ms referer=None
[W 2024-08-25 17:32:15.742 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 0.54ms referer=None
[I 2024-08-25 17:32:22.164 ServerApp] Kernel restarted: 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[I 2024-08-25 17:32:22.166 ServerApp] Starting buffering for 6b0485a9-18db-479b-bd8d-5b53ea62ebce:f9c6faaf-906c-4149-b498-06665890c50a
[I 2024-08-25 17:32:22.171 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[I 2024-08-25 17:32:22.171 ServerApp] Restoring connection for 6b0485a9-18db-479b-bd8d-5b53ea62ebce:f9c6faaf-906c-4149-b498-06665890c50a
[W 2024-08-26 02:22:45.624 ServerApp] 404 GET /hub/api (@10.0.0.99) 4.02ms referer=None
[I 2024-08-26 02:22:50.028 ServerApp] 302 GET / (@10.0.0.99) 0.35ms
[W 2024-08-26 02:22:50.031 ServerApp] 404 GET /hub/api (@10.0.0.99) 3.61ms referer=None
[I 2024-08-26 02:22:50.092 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.34ms
[I 2024-08-26 02:22:55.173 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[W 2024-08-26 02:23:00.389 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 2.64ms referer=None
[W 2024-08-26 02:23:00.390 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 0.59ms referer=None
[W 2024-08-26 02:23:00.391 ServerApp] 404 GET /hub/api (@10.0.0.99) 0.67ms referer=None
[W 2024-08-26 02:23:00.391 ServerApp] 404 GET /hub/api (@10.0.0.99) 1.02ms referer=None
[I 2024-08-26 02:23:00.408 ServerApp] 302 GET / (@10.0.0.99) 0.23ms
[I 2024-08-26 02:23:00.415 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.27ms
[W 2024-08-26 02:23:00.420 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 0.64ms referer=None
[W 2024-08-26 02:23:00.424 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 0.64ms referer=None
[W 2024-08-26 03:10:20.970 ServerApp] 404 GET /hub/api (@10.0.0.99) 3.86ms referer=None
[I 2024-08-26 03:10:20.972 ServerApp] 302 GET / (@10.0.0.99) 0.29ms
[I 2024-08-26 03:10:20.974 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.33ms
[I 2024-08-26 03:10:21.017 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[W 2024-08-26 03:10:26.163 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 2.46ms referer=None
[W 2024-08-26 03:10:26.164 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 0.73ms referer=None
[W 2024-08-26 03:10:26.164 ServerApp] 404 GET /hub/api (@10.0.0.99) 1.07ms referer=None
[W 2024-08-26 03:10:26.165 ServerApp] 404 GET /hub/api (@10.0.0.99) 0.59ms referer=None
[I 2024-08-26 03:10:26.231 ServerApp] 302 GET / (@10.0.0.99) 0.23ms
[I 2024-08-26 03:10:31.239 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.53ms
[W 2024-08-26 03:10:31.254 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 1.10ms referer=None
[W 2024-08-26 03:10:31.258 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 0.54ms referer=None
[W 2024-08-26 06:11:03.302 ServerApp] 404 GET /hub/api (@10.0.0.99) 4.54ms referer=None
[I 2024-08-26 06:11:03.305 ServerApp] 302 GET / (@10.0.0.99) 0.28ms
[I 2024-08-26 06:11:03.307 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.36ms
[I 2024-08-26 06:11:03.345 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[W 2024-08-26 06:11:08.526 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 17.41ms referer=None
[W 2024-08-26 06:11:08.527 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 0.84ms referer=None
[W 2024-08-26 06:11:08.528 ServerApp] 404 GET /hub/api (@10.0.0.99) 1.14ms referer=None
[W 2024-08-26 06:11:08.529 ServerApp] 404 GET /hub/api (@10.0.0.99) 1.09ms referer=None
[I 2024-08-26 06:11:08.569 ServerApp] 302 GET / (@10.0.0.99) 0.24ms
[I 2024-08-26 06:11:13.586 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.50ms
[W 2024-08-26 06:11:13.598 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.0.0.99) 1.02ms referer=None
[W 2024-08-26 06:11:13.599 ServerApp] 404 GET /nbextensions/viewer/extension.js (@10.0.0.99) 0.57ms referer=None
[W 2024-08-26 06:14:28.464 ServerApp] Wait for final termination of kernel timed out - continuing...
[I 2024-08-26 06:14:28.508 ServerApp] Kernel restarted: 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[I 2024-08-26 06:14:28.515 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
Traceback (most recent call last):
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 692, in initialize
    self.init_sockets()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 331, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 253, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 229, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/zmq/sugar/socket.py", line 302, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use (addr='tcp://127.0.0.1:52559')
[I 2024-08-26 06:14:31.500 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2024-08-26 06:14:31.500 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:31.501 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:31.501 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:31.519 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:2ea64e3f-c27a-4ca8-8d48-b6cae2f3e910
[I 2024-08-26 06:14:31.528 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[I 2024-08-26 06:14:31.529 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[I 2024-08-26 06:14:31.531 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
Traceback (most recent call last):
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 692, in initialize
    self.init_sockets()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 331, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 253, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 229, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/zmq/sugar/socket.py", line 302, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use (addr='tcp://127.0.0.1:52559')
[W 2024-08-26 06:14:33.027 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[I 2024-08-26 06:14:34.519 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (2/5), keep random ports
[W 2024-08-26 06:14:34.519 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:34.519 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d355060>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:34.531 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:34.532 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:34.532 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:34.543 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:7add88f0-cc76-4e31-b94b-ec2aa4da615d
[W 2024-08-26 06:14:34.544 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:acc5d108-5bf6-4452-aa79-12adfa8e86d0
[W 2024-08-26 06:14:34.545 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:2ea64e3f-c27a-4ca8-8d48-b6cae2f3e910
[I 2024-08-26 06:14:34.552 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[I 2024-08-26 06:14:34.554 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[I 2024-08-26 06:14:34.555 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
Traceback (most recent call last):
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 692, in initialize
    self.init_sockets()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 331, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 253, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 229, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/zmq/sugar/socket.py", line 302, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use (addr='tcp://127.0.0.1:52559')
[W 2024-08-26 06:14:36.040 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:36.041 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:36.041 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[I 2024-08-26 06:14:37.552 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (3/5), keep random ports
[W 2024-08-26 06:14:37.553 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:37.553 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d355060>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:37.557 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:37.557 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d356d10>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:37.557 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:37.557 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d3554e0>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:37.558 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:37.558 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d355900>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:37.558 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:37.558 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:37.558 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:37.568 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:7add88f0-cc76-4e31-b94b-ec2aa4da615d
[W 2024-08-26 06:14:37.570 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:acc5d108-5bf6-4452-aa79-12adfa8e86d0
[W 2024-08-26 06:14:37.570 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:2ea64e3f-c27a-4ca8-8d48-b6cae2f3e910
[I 2024-08-26 06:14:37.575 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[I 2024-08-26 06:14:37.576 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[I 2024-08-26 06:14:37.579 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[W 2024-08-26 06:14:38.046 ServerApp] Nudge: attempt 20 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
Traceback (most recent call last):
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 692, in initialize
    self.init_sockets()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 331, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 253, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 229, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/zmq/sugar/socket.py", line 302, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use (addr='tcp://127.0.0.1:52559')
[W 2024-08-26 06:14:39.065 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:39.066 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:39.066 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[I 2024-08-26 06:14:40.575 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (4/5), keep random ports
[W 2024-08-26 06:14:40.575 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:40.575 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d355060>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:40.581 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:40.581 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d356d10>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:40.581 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:40.581 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d3554e0>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:40.581 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:40.581 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d355900>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:40.582 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:40.582 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090ca669e0>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:40.582 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:40.582 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090ca67310>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:40.582 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:40.582 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090ca641f0>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:40.582 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:40.582 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:40.583 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:40.593 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:7add88f0-cc76-4e31-b94b-ec2aa4da615d
[W 2024-08-26 06:14:40.594 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:acc5d108-5bf6-4452-aa79-12adfa8e86d0
[W 2024-08-26 06:14:40.595 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:2ea64e3f-c27a-4ca8-8d48-b6cae2f3e910
[I 2024-08-26 06:14:40.605 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[I 2024-08-26 06:14:40.607 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[I 2024-08-26 06:14:40.608 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[W 2024-08-26 06:14:41.056 ServerApp] Nudge: attempt 20 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:41.056 ServerApp] Nudge: attempt 20 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:41.056 ServerApp] Nudge: attempt 20 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
Traceback (most recent call last):
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 692, in initialize
    self.init_sockets()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 331, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 253, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 229, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/zmq/sugar/socket.py", line 302, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use (addr='tcp://127.0.0.1:52559')
[W 2024-08-26 06:14:42.088 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:42.088 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:42.088 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:43.061 ServerApp] Nudge: attempt 30 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[I 2024-08-26 06:14:43.605 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), keep random ports
[W 2024-08-26 06:14:43.605 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:43.605 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d355060>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:43.609 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:43.609 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d356d10>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:43.609 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:43.609 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d3554e0>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:43.609 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:43.610 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d355900>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:43.610 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:43.610 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090ca669e0>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:43.610 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:43.610 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090ca67310>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:43.610 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:43.610 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090ca641f0>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:43.610 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:43.610 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090ca66d70>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:43.610 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:43.611 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090c123280>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:43.611 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[E 2024-08-26 06:14:43.611 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090c120880>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 786, in on_kernel_restarted
        self._send_status_message("restarting")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-08-26 06:14:43.611 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:43.611 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:43.611 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted
[W 2024-08-26 06:14:43.622 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:7add88f0-cc76-4e31-b94b-ec2aa4da615d
[W 2024-08-26 06:14:43.623 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:acc5d108-5bf6-4452-aa79-12adfa8e86d0
[I 2024-08-26 06:14:43.628 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[I 2024-08-26 06:14:43.629 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[W 2024-08-26 06:14:43.631 ServerApp] Replacing stale connection: 6b0485a9-18db-479b-bd8d-5b53ea62ebce:2ea64e3f-c27a-4ca8-8d48-b6cae2f3e910
[I 2024-08-26 06:14:43.638 ServerApp] Connecting to kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce.
[W 2024-08-26 06:14:44.079 ServerApp] Nudge: attempt 20 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:44.079 ServerApp] Nudge: attempt 20 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:44.079 ServerApp] Nudge: attempt 20 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
Traceback (most recent call last):
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 692, in initialize
    self.init_sockets()
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 331, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 253, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 229, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/zmq/sugar/socket.py", line 302, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use (addr='tcp://127.0.0.1:52559')
[W 2024-08-26 06:14:45.118 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:45.118 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:45.119 ServerApp] Nudge: attempt 10 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:46.068 ServerApp] Nudge: attempt 30 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:46.068 ServerApp] Nudge: attempt 30 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:46.069 ServerApp] Nudge: attempt 30 on kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:14:46.627 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2024-08-26 06:14:46.627 ServerApp] Kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce died, removing from map.
[W 2024-08-26 06:14:46.627 ServerApp] Restarting kernel failed: 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[E 2024-08-26 06:14:46.627 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.627 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d356d10>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.644 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.644 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d3554e0>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.644 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.644 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d355900>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.644 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.644 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090ca669e0>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.645 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.645 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090ca67310>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.645 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.645 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090ca641f0>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.645 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.645 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090ca66d70>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.645 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.645 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090c123280>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.645 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.645 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090c120880>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.646 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.646 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090d2bb850>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.646 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.646 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090c155960>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.646 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.646 ServerApp] KernelRestarter: dead callback <bound method ZMQChannelsWebsocketConnection.on_restart_failed of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x71090c155c60>> failed
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 791, in on_restart_failed
        self._send_status_message("dead")
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 781, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/websocket.py", line 332, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 2024-08-26 06:14:46.646 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.646 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[E 2024-08-26 06:14:46.647 ServerApp] kernel 6b0485a9-18db-479b-bd8d-5b53ea62ebce restarted failed!
[W 2024-08-26 06:14:46.648 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x710907f0e050>
[W 2024-08-26 06:14:46.648 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x710907f0e050>
[W 2024-08-26 06:14:47.123 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x71090c1563b0>
[W 2024-08-26 06:14:47.123 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x71090c1563b0>
[W 2024-08-26 06:14:47.123 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x71090c1571c0>
[W 2024-08-26 06:14:47.124 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x71090c1571c0>
[W 2024-08-26 06:14:47.124 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x710907f0c160>
[W 2024-08-26 06:14:47.124 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x710907f0c160>
[W 2024-08-26 06:14:57.947 ServerApp] 404 GET /hub/api (@10.0.0.99) 3.16ms referer=None
[I 2024-08-26 06:14:58.003 ServerApp] 302 GET / (@10.0.0.99) 0.25ms
[I 2024-08-26 06:15:03.004 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.46ms
[W 2024-08-26 06:15:03.045 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=28a5d9f2154ea379ef82cccb9bab7d61fbdfdc4d94058b88 (10.0.0.99): Kernel does not exist: 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:15:03.046 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=[secret] (36ef50def4844811970aa0f4d79133d9@10.0.0.99) 1.98ms referer=None
[W 2024-08-26 06:15:03.049 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=28a5d9f2154ea379ef82cccb9bab7d61fbdfdc4d94058b88 (10.0.0.99): Kernel does not exist: 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:15:03.049 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=[secret] (2bcd973c4de6445ea7eab226d1b14e3d@10.0.0.99) 0.81ms referer=None
[W 2024-08-26 06:15:03.696 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=28a5d9f2154ea379ef82cccb9bab7d61fbdfdc4d94058b88 (10.0.0.99): Kernel does not exist: 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:15:03.697 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=[secret] (2e535792bb944ddf83006392b42812ee@10.0.0.99) 1.28ms referer=None
[W 2024-08-26 06:15:04.249 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=28a5d9f2154ea379ef82cccb9bab7d61fbdfdc4d94058b88 (10.0.0.99): Kernel does not exist: 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:15:04.254 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=[secret] (4d5f2b115017425aa572f94cc465f6dd@10.0.0.99) 5.47ms referer=None
[W 2024-08-26 06:15:06.016 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=28a5d9f2154ea379ef82cccb9bab7d61fbdfdc4d94058b88 (10.0.0.99): Kernel does not exist: 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:15:06.020 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=[secret] (395e8107826c4b6f85791dcb63955a06@10.0.0.99) 4.31ms referer=None
[W 2024-08-26 06:15:17.996 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=28a5d9f2154ea379ef82cccb9bab7d61fbdfdc4d94058b88 (10.0.0.99): Kernel does not exist: 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:15:17.999 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=[secret] (eb99b0c5c5ec4becb584c1f8bb372100@10.0.0.99) 4.43ms referer=None
[W 2024-08-26 06:15:20.688 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=28a5d9f2154ea379ef82cccb9bab7d61fbdfdc4d94058b88 (10.0.0.99): Kernel does not exist: 6b0485a9-18db-479b-bd8d-5b53ea62ebce
[W 2024-08-26 06:15:20.702 ServerApp] 404 GET /api/kernels/6b0485a9-18db-479b-bd8d-5b53ea62ebce/channels?session_id=d5038ac7-4309-4e01-a390-46c0d4fc335f&token=[secret] (5b020f9da1884a139868a5788ebc087d@10.0.0.99) 13.85ms referer=None
[W 2024-08-26 06:15:35.632 ServerApp] 404 GET /hub/api (@10.0.0.99) 4.28ms referer=None
[I 2024-08-26 06:15:35.633 ServerApp] 302 GET / (@10.0.0.99) 0.21ms
[I 2024-08-26 06:15:35.635 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.29ms
[I 2024-08-26 06:15:35.686 ServerApp] Kernel started: 518047ec-5ab7-47a7-ad48-8ee95f747483
[I 2024-08-26 06:15:37.005 ServerApp] Connecting to kernel 518047ec-5ab7-47a7-ad48-8ee95f747483.
[I 2024-08-26 09:36:40.699 ServerApp] Starting buffering for 518047ec-5ab7-47a7-ad48-8ee95f747483:1a1a1104-99a6-492f-af5e-ad58c0fb5509
[W 2024-08-26 20:33:17.961 ServerApp] 404 GET /hub/api (@10.0.0.99) 3.92ms referer=None
[I 2024-08-26 20:33:22.664 ServerApp] 302 GET / (@10.0.0.99) 0.35ms
[I 2024-08-26 20:33:22.730 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.40ms
[W 2024-08-27 00:39:47.183 ServerApp] 404 GET /hub/api (@10.0.0.99) 3.79ms referer=None
[I 2024-08-27 00:39:47.277 ServerApp] 302 GET / (@10.0.0.99) 0.35ms
[I 2024-08-27 00:39:47.303 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.33ms
[W 2024-08-27 02:47:31.489 ServerApp] 404 GET /hub/api (@10.0.0.99) 4.31ms referer=None
[I 2024-08-27 02:47:36.451 ServerApp] 302 GET / (@10.0.0.99) 0.37ms
[I 2024-08-27 02:47:36.503 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.43ms
slurmstepd: error: *** JOB 11597 ON compute-permanent-node-535 CANCELLED AT 2024-08-27T03:31:40 DUE TO TIME LIMIT ***
