/var/spool/slurmd/job1415429/slurm_script: line 10: /data/[username]/anaconda3/etc/profile.d/conda.sh: No such file or directory

EnvironmentNameNotFound: Could not find conda environment: [environment]
You can list all discoverable environments with `conda info --envs`.


[I 2024-05-13 20:40:32.472 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-05-13 20:40:32.478 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2024-05-13 20:40:32.481 ServerApp] jupyterlab | error linking extension: Trait, kernel_name, not found.
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 346, in link_extension
        extension.link_all_points(self.serverapp)
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 228, in link_all_points
        self.link_point(point_name, serverapp)
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 218, in link_point
        point.link(serverapp)
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 140, in link
        linker(serverapp)
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/extension/application.py", line 404, in _link_jupyter_server_extension
        self.update_config(self.serverapp.config)
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/notebook_shim/shim.py", line 141, in update_config
        shimmed_config = self.shim_config_from_notebook_to_jupyter_server(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/notebook_shim/shim.py", line 232, in shim_config_from_notebook_to_jupyter_server
        raise TraitError("Trait, {}, not found.".format(trait_name))
    traitlets.traitlets.TraitError: Trait, kernel_name, not found.
[I 2024-05-13 20:40:32.489 ServerApp] notebook | extension was successfully linked.
[I 2024-05-13 20:40:33.055 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-05-13 20:40:33.104 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-05-13 20:40:33.106 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-05-13 20:40:33.107 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-05-13 20:40:33.120 LabApp] JupyterLab extension loaded from /data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyterlab
[I 2024-05-13 20:40:33.120 LabApp] JupyterLab application directory is /data/tianyu_guo/miniconda3/share/jupyter/lab
[I 2024-05-13 20:40:33.121 LabApp] Extension Manager is 'pypi'.
[I 2024-05-13 20:40:33.130 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-05-13 20:40:33.138 ServerApp] notebook | extension was successfully loaded.
[I 2024-05-13 20:40:33.138 ServerApp] Serving notebooks from local directory: /data/tianyu_guo/birth
[I 2024-05-13 20:40:33.138 ServerApp] Jupyter Server 2.14.0 is running at:
[I 2024-05-13 20:40:33.138 ServerApp] http://compute-permanent-node-800:8888/tree?token=f31a565e1877fb045e6cc73bc84f8a403628aa6f4ba8b034
[I 2024-05-13 20:40:33.138 ServerApp]     http://127.0.0.1:8888/tree?token=f31a565e1877fb045e6cc73bc84f8a403628aa6f4ba8b034
[I 2024-05-13 20:40:33.138 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-05-13 20:40:33.142 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///data/tianyu_guo/.local/share/jupyter/runtime/jpserver-194755-open.html
    Or copy and paste one of these URLs:
        http://compute-permanent-node-800:8888/tree?token=f31a565e1877fb045e6cc73bc84f8a403628aa6f4ba8b034
        http://127.0.0.1:8888/tree?token=f31a565e1877fb045e6cc73bc84f8a403628aa6f4ba8b034
[I 2024-05-13 20:40:33.604 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-05-13 20:40:58.138 ServerApp] Couldn't authenticate WebSocket connection
[W 2024-05-13 20:40:58.157 ServerApp] 403 GET /api/kernels/18bdbb8d-6c4b-4003-8a79-1cc3fa96bc91/channels?session_id=dd94f831-4796-4fbe-8ba9-69872e4ff1a8&token=[secret] (@172.16.0.238) 19.47ms referer=None
[W 2024-05-13 20:41:03.844 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-13 20:41:03.849 ServerApp] 403 GET /api/kernelspecs?1715632862654 (@172.16.0.238) 6.18ms referer=None
[W 2024-05-13 20:41:03.850 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-13 20:41:03.850 ServerApp] 403 GET /api/kernels?1715632862656 (@172.16.0.238) 0.60ms referer=None
[W 2024-05-13 20:41:04.883 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-13 20:41:04.885 ServerApp] 403 GET /api/kernels?1715632862658 (@172.16.0.238) 2.76ms referer=None
[W 2024-05-13 20:41:04.885 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-13 20:41:04.886 ServerApp] 403 GET /api/sessions?1715632862659 (@172.16.0.238) 0.56ms referer=None
[W 2024-05-13 20:41:07.026 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-13 20:41:07.028 ServerApp] 403 GET /api/kernelspecs?1715632864882 (@172.16.0.238) 2.85ms referer=None
[W 2024-05-13 20:41:08.061 ServerApp] 404 GET /hub/api (@172.16.0.238) 4.48ms referer=None
[I 2024-05-13 20:41:11.082 ServerApp] 302 GET / (@172.16.0.238) 0.26ms
[I 2024-05-13 20:41:14.283 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.46ms
[W 2024-05-13 20:41:20.515 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-13 20:41:20.518 ServerApp] 403 GET /api/kernelspecs?1715632878293 (@172.16.0.238) 3.30ms referer=None
[W 2024-05-13 20:41:20.519 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-13 20:41:20.519 ServerApp] 403 GET /api/kernels?1715632878295 (@172.16.0.238) 0.88ms referer=None
[W 2024-05-13 20:41:20.519 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-13 20:41:20.520 ServerApp] 403 GET /api/kernels?1715632878296 (@172.16.0.238) 1.23ms referer=None
[W 2024-05-13 20:41:20.520 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-13 20:41:20.520 ServerApp] 403 GET /api/sessions?1715632878297 (@172.16.0.238) 1.60ms referer=None
[W 2024-05-14 12:52:20.305 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.30ms referer=None
[I 2024-05-14 12:52:20.442 ServerApp] 302 GET / (@172.16.0.238) 0.24ms
[I 2024-05-14 12:52:20.479 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.60ms
[W 2024-05-14 12:52:20.566 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.568 ServerApp] 403 GET /api/kernelspecs?1715691140533 (@172.16.0.238) 2.73ms referer=None
[W 2024-05-14 12:52:20.569 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.569 ServerApp] 403 GET /api/kernels?1715691140534 (@172.16.0.238) 0.74ms referer=None
[W 2024-05-14 12:52:20.569 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.570 ServerApp] 403 GET /api/kernelspecs?1715691140535 (@172.16.0.238) 1.10ms referer=None
[W 2024-05-14 12:52:20.570 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.570 ServerApp] 403 GET /api/kernels?1715691140537 (@172.16.0.238) 0.57ms referer=None
[W 2024-05-14 12:52:20.574 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.574 ServerApp] 403 GET /api/kernels?1715691140549 (@172.16.0.238) 1.03ms referer=None
[W 2024-05-14 12:52:20.575 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.575 ServerApp] 403 GET /api/sessions?1715691140550 (@172.16.0.238) 0.59ms referer=None
[W 2024-05-14 12:52:20.575 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.576 ServerApp] 403 GET /api/kernels?1715691140551 (@172.16.0.238) 0.68ms referer=None
[W 2024-05-14 12:52:20.576 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.576 ServerApp] 403 GET /api/sessions?1715691140553 (@172.16.0.238) 1.05ms referer=None
[W 2024-05-14 12:52:20.606 ServerApp] 404 GET /hub/api (@172.16.0.238) 0.93ms referer=None
[W 2024-05-14 12:52:20.614 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.614 ServerApp] 403 GET /api/kernelspecs?1715691140590 (@172.16.0.238) 0.98ms referer=None
[W 2024-05-14 12:52:20.624 ServerApp] 404 GET /hub/api (@172.16.0.238) 1.24ms referer=None
[I 2024-05-14 12:52:20.632 ServerApp] 302 GET / (@172.16.0.238) 0.26ms
[I 2024-05-14 12:52:20.651 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.60ms
[W 2024-05-14 12:52:20.677 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.677 ServerApp] 403 GET /api/kernelspecs?1715691140665 (@172.16.0.238) 1.14ms referer=None
[W 2024-05-14 12:52:20.678 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.678 ServerApp] 403 GET /api/kernels?1715691140666 (@172.16.0.238) 0.68ms referer=None
[W 2024-05-14 12:52:20.679 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.679 ServerApp] 403 GET /api/kernelspecs?1715691140667 (@172.16.0.238) 0.73ms referer=None
[W 2024-05-14 12:52:20.679 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.680 ServerApp] 403 GET /api/kernels?1715691140668 (@172.16.0.238) 1.08ms referer=None
[W 2024-05-14 12:52:20.680 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.681 ServerApp] 403 GET /api/kernels?1715691140669 (@172.16.0.238) 0.95ms referer=None
[W 2024-05-14 12:52:20.681 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.681 ServerApp] 403 GET /api/sessions?1715691140671 (@172.16.0.238) 1.32ms referer=None
[W 2024-05-14 12:52:20.681 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.682 ServerApp] 403 GET /api/kernels?1715691140672 (@172.16.0.238) 1.68ms referer=None
[W 2024-05-14 12:52:20.682 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.682 ServerApp] 403 GET /api/sessions?1715691140673 (@172.16.0.238) 2.04ms referer=None
[W 2024-05-14 12:52:20.691 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.692 ServerApp] 403 GET /api/kernelspecs?1715691140681 (@172.16.0.238) 1.00ms referer=None
[W 2024-05-14 12:52:20.692 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-14 12:52:20.693 ServerApp] 403 GET /api/kernelspecs?1715691140684 (@172.16.0.238) 0.64ms referer=None
[W 2024-05-15 02:18:32.772 ServerApp] 404 GET /hub/api (@172.16.0.238) 6.82ms referer=None
[I 2024-05-15 02:18:32.776 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.34ms
[W 2024-05-15 02:18:33.927 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.43ms referer=None
[I 2024-05-15 02:18:33.929 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.29ms
[W 2024-05-15 02:18:37.572 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.11ms referer=None
[I 2024-05-15 02:18:37.592 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.31ms
[I 2024-05-15 02:18:37.661 ServerApp] Kernel started: 26a99197-3164-4305-bfb8-0bd6a1431894
[I 2024-05-15 02:18:38.831 ServerApp] Connecting to kernel 26a99197-3164-4305-bfb8-0bd6a1431894.
[I 2024-05-15 02:18:40.093 ServerApp] Starting buffering for 26a99197-3164-4305-bfb8-0bd6a1431894:519f774e-3d3d-4bdf-b042-a77f5e7f525f
[W 2024-05-15 02:18:51.361 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.71ms referer=None
[I 2024-05-15 02:18:51.367 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.50ms
[I 2024-05-15 02:18:51.415 ServerApp] Kernel started: b8105118-f6fc-4098-947d-c626dc2699c9
[I 2024-05-15 02:18:52.081 ServerApp] Connecting to kernel b8105118-f6fc-4098-947d-c626dc2699c9.
[I 2024-05-15 07:31:10.043 ServerApp] Starting buffering for b8105118-f6fc-4098-947d-c626dc2699c9:dadda829-5709-4b12-abed-f04c9b741be5
[W 2024-05-15 11:40:37.850 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.77ms referer=None
[I 2024-05-15 11:40:38.092 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.64ms
[W 2024-05-15 11:40:53.061 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.09ms referer=None
[I 2024-05-15 11:40:53.066 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.59ms
[I 2024-05-15 11:40:53.141 ServerApp] Connecting to kernel b8105118-f6fc-4098-947d-c626dc2699c9.
[W 2024-05-15 11:40:54.566 ServerApp] 404 GET /nbextensions/viewer/extension.js (@172.16.0.238) 3.80ms referer=None
[W 2024-05-15 11:40:54.566 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@172.16.0.238) 4.36ms referer=None
[W 2024-05-15 11:40:54.567 ServerApp] 404 GET /hub/api (@172.16.0.238) 4.91ms referer=None
[W 2024-05-15 11:40:54.568 ServerApp] 404 GET /hub/api (@172.16.0.238) 5.45ms referer=None
[I 2024-05-15 11:40:54.570 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.58ms
[W 2024-05-15 11:40:54.575 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@172.16.0.238) 1.05ms referer=None
[W 2024-05-15 11:40:54.575 ServerApp] 404 GET /nbextensions/viewer/extension.js (@172.16.0.238) 1.59ms referer=None
