/var/spool/slurmd/job09386/slurm_script: line 10: /data/[username]/anaconda3/etc/profile.d/conda.sh: No such file or directory
[I 2024-08-21 02:33:46.519 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-08-21 02:33:46.525 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2024-08-21 02:33:46.528 ServerApp] jupyterlab | error linking extension: Trait, kernel_name, not found.
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 346, in link_extension
        extension.link_all_points(self.serverapp)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 228, in link_all_points
        self.link_point(point_name, serverapp)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 218, in link_point
        point.link(serverapp)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 140, in link
        linker(serverapp)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 404, in _link_jupyter_server_extension
        self.update_config(self.serverapp.config)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/notebook_shim/shim.py", line 141, in update_config
        shimmed_config = self.shim_config_from_notebook_to_jupyter_server(
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/notebook_shim/shim.py", line 232, in shim_config_from_notebook_to_jupyter_server
        raise TraitError("Trait, {}, not found.".format(trait_name))
    traitlets.traitlets.TraitError: Trait, kernel_name, not found.
[I 2024-08-21 02:33:46.536 ServerApp] notebook | extension was successfully linked.
[I 2024-08-21 02:33:47.092 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-08-21 02:33:47.139 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-08-21 02:33:47.140 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-08-21 02:33:47.142 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-08-21 02:33:47.155 LabApp] JupyterLab extension loaded from /data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyterlab
[I 2024-08-21 02:33:47.155 LabApp] JupyterLab application directory is /data/tianyu_guo/miniconda3/envs/nanogpt/share/jupyter/lab
[I 2024-08-21 02:33:47.156 LabApp] Extension Manager is 'pypi'.
[I 2024-08-21 02:33:47.177 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-08-21 02:33:47.193 ServerApp] notebook | extension was successfully loaded.
[I 2024-08-21 02:33:47.193 ServerApp] The port 8888 is already in use, trying another port.
[I 2024-08-21 02:33:47.194 ServerApp] Serving notebooks from local directory: /data/tianyu_guo/birth
[I 2024-08-21 02:33:47.194 ServerApp] Jupyter Server 2.14.0 is running at:
[I 2024-08-21 02:33:47.194 ServerApp] http://compute-permanent-node-845:8889/tree?token=d66382de708faa81bcaadc75b16cb91e7798c0e5068f7f2c
[I 2024-08-21 02:33:47.194 ServerApp]     http://127.0.0.1:8889/tree?token=d66382de708faa81bcaadc75b16cb91e7798c0e5068f7f2c
[I 2024-08-21 02:33:47.194 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-08-21 02:33:47.199 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///data/tianyu_guo/.local/share/jupyter/runtime/jpserver-491787-open.html
    Or copy and paste one of these URLs:
        http://compute-permanent-node-845:8889/tree?token=d66382de708faa81bcaadc75b16cb91e7798c0e5068f7f2c
        http://127.0.0.1:8889/tree?token=d66382de708faa81bcaadc75b16cb91e7798c0e5068f7f2c
[I 2024-08-21 02:33:47.289 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-08-21 04:30:48.158 ServerApp] 404 GET /hub/api (@10.0.0.99) 26.15ms referer=None
[I 2024-08-21 04:30:48.204 ServerApp] 302 GET / (@10.0.0.99) 0.29ms
[I 2024-08-21 04:30:48.225 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.36ms
[W 2024-08-21 04:30:48.292 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 04:30:48.296 ServerApp] 403 GET /api/kernelspecs?1724214648289 (@10.0.0.99) 4.50ms referer=None
[W 2024-08-21 04:30:48.297 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 04:30:48.297 ServerApp] 403 GET /api/kernels?1724214648290 (@10.0.0.99) 1.04ms referer=None
[W 2024-08-21 04:30:48.298 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 04:30:48.298 ServerApp] 403 GET /api/sessions?1724214648294 (@10.0.0.99) 1.29ms referer=None
[W 2024-08-21 04:30:48.298 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 04:30:48.298 ServerApp] 403 GET /api/kernels?1724214648293 (@10.0.0.99) 1.53ms referer=None
[W 2024-08-21 04:30:48.382 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 04:30:48.382 ServerApp] 403 GET /api/kernelspecs?1724214648296 (@10.0.0.99) 0.67ms referer=None
[W 2024-08-21 04:30:48.384 ServerApp] 404 GET /hub/api (@10.0.0.99) 0.94ms referer=None
[I 2024-08-21 04:30:48.387 ServerApp] 302 GET / (@10.0.0.99) 0.33ms
[I 2024-08-21 04:30:48.390 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.43ms
[W 2024-08-21 04:30:48.400 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 04:30:48.401 ServerApp] 403 GET /api/kernelspecs?1724214648398 (@10.0.0.99) 0.55ms referer=None
[W 2024-08-21 04:30:48.405 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 04:30:48.405 ServerApp] 403 GET /api/kernels?1724214648399 (@10.0.0.99) 0.56ms referer=None
[W 2024-08-21 04:30:48.406 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 04:30:48.406 ServerApp] 403 GET /api/kernels?1724214648400 (@10.0.0.99) 0.90ms referer=None
[W 2024-08-21 04:30:48.407 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 04:30:48.408 ServerApp] 403 GET /api/sessions?1724214648401 (@10.0.0.99) 1.10ms referer=None
[W 2024-08-21 04:30:48.408 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 04:30:48.408 ServerApp] 403 GET /api/kernelspecs?1724214648403 (@10.0.0.99) 1.39ms referer=None
[W 2024-08-21 05:07:55.247 ServerApp] 404 GET /hub/api (@10.0.0.99) 14.81ms referer=None
[I 2024-08-21 05:07:55.369 ServerApp] 302 GET / (@10.0.0.99) 0.36ms
[I 2024-08-21 05:07:55.445 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.44ms
[W 2024-08-21 05:07:55.510 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 05:07:55.512 ServerApp] 403 GET /api/kernelspecs?1724216875508 (@10.0.0.99) 1.58ms referer=None
[W 2024-08-21 05:07:55.521 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 05:07:55.522 ServerApp] 403 GET /api/kernels?1724216875509 (@10.0.0.99) 0.92ms referer=None
[W 2024-08-21 05:07:55.523 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 05:07:55.523 ServerApp] 403 GET /api/kernels?1724216875514 (@10.0.0.99) 1.05ms referer=None
[W 2024-08-21 05:07:55.524 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 05:07:55.524 ServerApp] 403 GET /api/kernelspecs?1724216875519 (@10.0.0.99) 1.61ms referer=None
[W 2024-08-21 05:07:55.524 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 05:07:55.525 ServerApp] 403 GET /api/sessions?1724216875514 (@10.0.0.99) 1.30ms referer=None
[W 2024-08-21 05:07:55.604 ServerApp] 404 GET /hub/api (@10.0.0.99) 0.89ms referer=None
[I 2024-08-21 05:07:55.608 ServerApp] 302 GET / (@10.0.0.99) 0.32ms
[I 2024-08-21 05:07:55.612 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.42ms
[W 2024-08-21 05:07:55.622 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 05:07:55.622 ServerApp] 403 GET /api/kernelspecs?1724216875619 (@10.0.0.99) 0.57ms referer=None
[W 2024-08-21 05:07:55.626 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 05:07:55.626 ServerApp] 403 GET /api/kernels?1724216875620 (@10.0.0.99) 0.57ms referer=None
[W 2024-08-21 05:07:55.633 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 05:07:55.633 ServerApp] 403 GET /api/kernels?1724216875623 (@10.0.0.99) 0.52ms referer=None
[W 2024-08-21 05:07:55.634 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 05:07:55.634 ServerApp] 403 GET /api/sessions?1724216875624 (@10.0.0.99) 0.54ms referer=None
[W 2024-08-21 05:07:55.637 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 05:07:55.637 ServerApp] 403 GET /api/kernelspecs?1724216875627 (@10.0.0.99) 0.46ms referer=None
[W 2024-08-21 08:08:54.037 ServerApp] 404 GET /hub/api (@10.0.0.99) 3.43ms referer=None
[I 2024-08-21 08:08:54.084 ServerApp] 302 GET / (@10.0.0.99) 0.26ms
[I 2024-08-21 08:08:54.114 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.33ms
[W 2024-08-21 08:08:54.182 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 08:08:54.184 ServerApp] 403 GET /api/kernelspecs?1724227734180 (@10.0.0.99) 1.51ms referer=None
[W 2024-08-21 08:08:54.192 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 08:08:54.192 ServerApp] 403 GET /api/kernels?1724227734181 (@10.0.0.99) 0.51ms referer=None
[W 2024-08-21 08:08:54.193 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 08:08:54.193 ServerApp] 403 GET /api/kernels?1724227734184 (@10.0.0.99) 0.72ms referer=None
[W 2024-08-21 08:08:54.194 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 08:08:54.194 ServerApp] 403 GET /api/kernelspecs?1724227734189 (@10.0.0.99) 1.07ms referer=None
[W 2024-08-21 08:08:54.194 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 08:08:54.194 ServerApp] 403 GET /api/sessions?1724227734185 (@10.0.0.99) 0.88ms referer=None
[W 2024-08-21 08:08:54.200 ServerApp] 404 GET /hub/api (@10.0.0.99) 0.57ms referer=None
[I 2024-08-21 08:08:54.287 ServerApp] 302 GET / (@10.0.0.99) 0.21ms
[I 2024-08-21 08:08:54.291 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.30ms
[W 2024-08-21 08:08:54.302 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 08:08:54.302 ServerApp] 403 GET /api/kernelspecs?1724227734300 (@10.0.0.99) 0.55ms referer=None
[W 2024-08-21 08:08:54.307 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 08:08:54.307 ServerApp] 403 GET /api/kernels?1724227734301 (@10.0.0.99) 0.57ms referer=None
[W 2024-08-21 08:08:54.309 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 08:08:54.309 ServerApp] 403 GET /api/kernels?1724227734305 (@10.0.0.99) 0.46ms referer=None
[W 2024-08-21 08:08:54.310 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 08:08:54.310 ServerApp] 403 GET /api/sessions?1724227734306 (@10.0.0.99) 0.46ms referer=None
[W 2024-08-21 08:08:54.311 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 08:08:54.311 ServerApp] 403 GET /api/kernelspecs?1724227734307 (@10.0.0.99) 0.44ms referer=None
[W 2024-08-21 17:45:03.583 ServerApp] 404 GET /hub/api (@10.0.0.99) 3.75ms referer=None
[I 2024-08-21 17:45:09.677 ServerApp] 302 GET / (@10.0.0.99) 0.29ms
[I 2024-08-21 17:45:09.704 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.52ms
[W 2024-08-21 17:45:09.794 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 17:45:09.795 ServerApp] 403 GET /api/kernelspecs?1724262309792 (@10.0.0.99) 1.44ms referer=None
[W 2024-08-21 17:45:09.796 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 17:45:09.796 ServerApp] 403 GET /api/kernels?1724262309792 (@10.0.0.99) 0.91ms referer=None
[W 2024-08-21 17:45:09.796 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 17:45:09.796 ServerApp] 403 GET /api/kernels?1724262309793 (@10.0.0.99) 1.09ms referer=None
[W 2024-08-21 17:45:09.797 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 17:45:09.797 ServerApp] 403 GET /api/sessions?1724262309794 (@10.0.0.99) 1.30ms referer=None
[W 2024-08-21 17:45:09.800 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 17:45:09.800 ServerApp] 403 GET /api/kernelspecs?1724262309796 (@10.0.0.99) 0.84ms referer=None
[W 2024-08-21 17:45:09.802 ServerApp] 404 GET /hub/api (@10.0.0.99) 1.10ms referer=None
[I 2024-08-21 17:45:09.804 ServerApp] 302 GET / (@10.0.0.99) 0.21ms
[I 2024-08-21 17:45:09.805 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.27ms
[W 2024-08-21 17:45:09.900 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 17:45:09.900 ServerApp] 403 GET /api/kernelspecs?1724262309899 (@10.0.0.99) 0.48ms referer=None
[W 2024-08-21 17:45:09.956 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 17:45:09.956 ServerApp] 403 GET /api/kernels?1724262309899 (@10.0.0.99) 0.63ms referer=None
[W 2024-08-21 17:45:09.956 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 17:45:09.957 ServerApp] 403 GET /api/kernels?1724262309900 (@10.0.0.99) 0.51ms referer=None
[W 2024-08-21 17:45:09.957 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 17:45:09.957 ServerApp] 403 GET /api/sessions?1724262309900 (@10.0.0.99) 0.50ms referer=None
[W 2024-08-21 17:45:09.958 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 17:45:09.958 ServerApp] 403 GET /api/kernelspecs?1724262309947 (@10.0.0.99) 0.49ms referer=None
[W 2024-08-21 19:17:23.179 ServerApp] 404 GET /hub/api (@10.0.0.99) 4.03ms referer=None
[I 2024-08-21 19:17:29.136 ServerApp] 302 GET / (@10.0.0.99) 0.45ms
[I 2024-08-21 19:17:29.181 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.36ms
[W 2024-08-21 19:17:29.283 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 19:17:29.285 ServerApp] 403 GET /api/kernelspecs?1724267849282 (@10.0.0.99) 1.62ms referer=None
[W 2024-08-21 19:17:29.286 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 19:17:29.286 ServerApp] 403 GET /api/kernels?1724267849282 (@10.0.0.99) 0.91ms referer=None
[W 2024-08-21 19:17:29.286 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 19:17:29.286 ServerApp] 403 GET /api/kernels?1724267849283 (@10.0.0.99) 1.09ms referer=None
[W 2024-08-21 19:17:29.287 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 19:17:29.287 ServerApp] 403 GET /api/sessions?1724267849284 (@10.0.0.99) 1.29ms referer=None
[W 2024-08-21 19:17:29.290 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 19:17:29.290 ServerApp] 403 GET /api/kernelspecs?1724267849286 (@10.0.0.99) 0.46ms referer=None
[W 2024-08-21 19:17:29.291 ServerApp] 404 GET /hub/api (@10.0.0.99) 1.03ms referer=None
[I 2024-08-21 19:17:29.293 ServerApp] 302 GET / (@10.0.0.99) 0.21ms
[I 2024-08-21 19:17:29.294 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.27ms
[W 2024-08-21 19:17:29.377 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 19:17:29.377 ServerApp] 403 GET /api/kernelspecs?1724267849376 (@10.0.0.99) 0.77ms referer=None
[W 2024-08-21 19:17:29.381 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 19:17:29.381 ServerApp] 403 GET /api/kernels?1724267849376 (@10.0.0.99) 0.49ms referer=None
[W 2024-08-21 19:17:29.381 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 19:17:29.382 ServerApp] 403 GET /api/kernels?1724267849377 (@10.0.0.99) 0.46ms referer=None
[W 2024-08-21 19:17:29.382 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 19:17:29.382 ServerApp] 403 GET /api/sessions?1724267849377 (@10.0.0.99) 0.55ms referer=None
[W 2024-08-21 19:17:29.387 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 19:17:29.387 ServerApp] 403 GET /api/kernelspecs?1724267849380 (@10.0.0.99) 0.78ms referer=None
[W 2024-08-21 21:36:07.362 ServerApp] 404 GET /hub/api (@10.0.0.99) 4.11ms referer=None
[I 2024-08-21 21:36:11.893 ServerApp] 302 GET / (@10.0.0.99) 0.29ms
[I 2024-08-21 21:36:11.959 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.35ms
[W 2024-08-21 21:36:12.178 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 21:36:12.179 ServerApp] 403 GET /api/kernelspecs?1724276172175 (@10.0.0.99) 1.63ms referer=None
[W 2024-08-21 21:36:12.181 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 21:36:12.181 ServerApp] 403 GET /api/kernels?1724276172176 (@10.0.0.99) 0.50ms referer=None
[W 2024-08-21 21:36:12.182 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 21:36:12.182 ServerApp] 403 GET /api/kernels?1724276172178 (@10.0.0.99) 0.69ms referer=None
[W 2024-08-21 21:36:12.183 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 21:36:12.183 ServerApp] 403 GET /api/kernelspecs?1724276172180 (@10.0.0.99) 1.05ms referer=None
[W 2024-08-21 21:36:12.183 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 21:36:12.183 ServerApp] 403 GET /api/sessions?1724276172178 (@10.0.0.99) 0.88ms referer=None
[W 2024-08-21 21:36:12.187 ServerApp] 404 GET /hub/api (@10.0.0.99) 1.04ms referer=None
[I 2024-08-21 21:36:12.188 ServerApp] 302 GET / (@10.0.0.99) 0.21ms
[I 2024-08-21 21:36:12.190 JupyterNotebookApp] 302 GET /tree? (@10.0.0.99) 0.28ms
[W 2024-08-21 21:36:15.045 ServerApp] 401 POST /login? (@10.0.0.99) 0.59ms referer=None
[W 2024-08-21 21:36:15.050 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 21:36:15.051 ServerApp] 403 GET /api/kernelspecs?1724276175048 (@10.0.0.99) 1.37ms referer=None
[W 2024-08-21 21:36:15.052 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 21:36:15.053 ServerApp] 403 GET /api/kernels?1724276175049 (@10.0.0.99) 0.91ms referer=None
[W 2024-08-21 21:36:15.053 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 21:36:15.053 ServerApp] 403 GET /api/kernels?1724276175049 (@10.0.0.99) 1.10ms referer=None
[W 2024-08-21 21:36:15.053 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 21:36:15.054 ServerApp] 403 GET /api/sessions?1724276175050 (@10.0.0.99) 1.30ms referer=None
[W 2024-08-21 21:36:15.054 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/data/tianyu_guo/miniconda3/envs/nanogpt/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-08-21 21:36:15.054 ServerApp] 403 GET /api/kernelspecs?1724276175051 (@10.0.0.99) 0.48ms referer=None
slurmstepd: error: *** JOB 9386 ON compute-permanent-node-845 CANCELLED AT 2024-08-22T21:14:58 ***
