/var/spool/slurmd/job1438999/slurm_script: line 10: /data/[username]/anaconda3/etc/profile.d/conda.sh: No such file or directory

EnvironmentNameNotFound: Could not find conda environment: [environment]
You can list all discoverable environments with `conda info --envs`.


[I 2024-05-19 03:35:37.946 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-05-19 03:35:37.951 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2024-05-19 03:35:37.954 ServerApp] jupyterlab | error linking extension: Trait, kernel_name, not found.
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 346, in link_extension
        extension.link_all_points(self.serverapp)
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 228, in link_all_points
        self.link_point(point_name, serverapp)
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 218, in link_point
        point.link(serverapp)
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 140, in link
        linker(serverapp)
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/extension/application.py", line 404, in _link_jupyter_server_extension
        self.update_config(self.serverapp.config)
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/notebook_shim/shim.py", line 141, in update_config
        shimmed_config = self.shim_config_from_notebook_to_jupyter_server(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/notebook_shim/shim.py", line 232, in shim_config_from_notebook_to_jupyter_server
        raise TraitError("Trait, {}, not found.".format(trait_name))
    traitlets.traitlets.TraitError: Trait, kernel_name, not found.
[I 2024-05-19 03:35:37.962 ServerApp] notebook | extension was successfully linked.
[I 2024-05-19 03:35:38.541 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-05-19 03:35:38.589 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-05-19 03:35:38.591 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-05-19 03:35:38.592 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-05-19 03:35:38.605 LabApp] JupyterLab extension loaded from /data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyterlab
[I 2024-05-19 03:35:38.605 LabApp] JupyterLab application directory is /data/tianyu_guo/miniconda3/share/jupyter/lab
[I 2024-05-19 03:35:38.606 LabApp] Extension Manager is 'pypi'.
[I 2024-05-19 03:35:38.615 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-05-19 03:35:38.623 ServerApp] notebook | extension was successfully loaded.
[I 2024-05-19 03:35:38.623 ServerApp] Serving notebooks from local directory: /data/tianyu_guo/birth
[I 2024-05-19 03:35:38.623 ServerApp] Jupyter Server 2.14.0 is running at:
[I 2024-05-19 03:35:38.623 ServerApp] http://compute-permanent-node-166:8888/tree?token=66d20914ac056711ddeeccec8ef9b34c92596ea54a9ad506
[I 2024-05-19 03:35:38.623 ServerApp]     http://127.0.0.1:8888/tree?token=66d20914ac056711ddeeccec8ef9b34c92596ea54a9ad506
[I 2024-05-19 03:35:38.623 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-05-19 03:35:38.649 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///data/tianyu_guo/.local/share/jupyter/runtime/jpserver-100189-open.html
    Or copy and paste one of these URLs:
        http://compute-permanent-node-166:8888/tree?token=66d20914ac056711ddeeccec8ef9b34c92596ea54a9ad506
        http://127.0.0.1:8888/tree?token=66d20914ac056711ddeeccec8ef9b34c92596ea54a9ad506
[I 2024-05-19 03:35:39.114 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-05-19 03:56:46.150 ServerApp] 404 GET /hub/api (@172.16.0.238) 22.07ms referer=None
[I 2024-05-19 03:56:46.156 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.67ms
[W 2024-05-19 03:56:46.164 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 03:56:46.169 ServerApp] 403 GET /api/kernelspecs?1716091006160 (@172.16.0.238) 4.95ms referer=None
[W 2024-05-19 03:56:46.170 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 03:56:46.170 ServerApp] 403 GET /api/kernels?1716091006161 (@172.16.0.238) 0.89ms referer=None
[W 2024-05-19 03:56:46.170 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 03:56:46.171 ServerApp] 403 GET /api/kernels?1716091006161 (@172.16.0.238) 1.33ms referer=None
[W 2024-05-19 03:56:46.171 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 03:56:46.171 ServerApp] 403 GET /api/sessions?1716091006162 (@172.16.0.238) 1.70ms referer=None
[W 2024-05-19 04:20:37.947 ServerApp] 404 GET /hub/api (@172.16.0.238) 4.73ms referer=None
[I 2024-05-19 04:20:37.953 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.28ms
[W 2024-05-19 04:20:37.967 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:20:37.969 ServerApp] 403 GET /api/kernelspecs?1716092437955 (@172.16.0.238) 2.94ms referer=None
[W 2024-05-19 04:20:37.970 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:20:37.971 ServerApp] 403 GET /api/kernels?1716092437957 (@172.16.0.238) 1.17ms referer=None
[W 2024-05-19 04:20:37.971 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:20:37.971 ServerApp] 403 GET /api/kernels?1716092437959 (@172.16.0.238) 1.55ms referer=None
[W 2024-05-19 04:20:37.971 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:20:37.972 ServerApp] 403 GET /api/sessions?1716092437960 (@172.16.0.238) 1.97ms referer=None
[W 2024-05-19 04:25:09.459 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.05ms referer=None
[I 2024-05-19 04:25:09.538 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.31ms
[W 2024-05-19 04:25:09.572 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:25:09.573 ServerApp] 403 GET /api/kernelspecs?1716092709561 (@172.16.0.238) 2.04ms referer=None
[W 2024-05-19 04:25:09.574 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:25:09.574 ServerApp] 403 GET /api/sessions?1716092709569 (@172.16.0.238) 0.68ms referer=None
[W 2024-05-19 04:25:09.575 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:25:09.575 ServerApp] 403 GET /api/kernels?1716092709562 (@172.16.0.238) 0.59ms referer=None
[W 2024-05-19 04:25:09.575 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:25:09.576 ServerApp] 403 GET /api/kernels?1716092709567 (@172.16.0.238) 0.58ms referer=None
[W 2024-05-19 04:25:09.581 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:25:09.581 ServerApp] 403 GET /api/kernelspecs?1716092709575 (@172.16.0.238) 1.20ms referer=None
[W 2024-05-19 04:48:46.253 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.19ms referer=None
[I 2024-05-19 04:48:46.341 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.39ms
[W 2024-05-19 04:48:46.386 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:48:46.388 ServerApp] 403 GET /api/kernelspecs?1716094126373 (@172.16.0.238) 1.92ms referer=None
[W 2024-05-19 04:48:46.388 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:48:46.389 ServerApp] 403 GET /api/kernels?1716094126374 (@172.16.0.238) 1.07ms referer=None
[W 2024-05-19 04:48:46.389 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:48:46.389 ServerApp] 403 GET /api/kernels?1716094126380 (@172.16.0.238) 1.46ms referer=None
[W 2024-05-19 04:48:46.390 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:48:46.390 ServerApp] 403 GET /api/sessions?1716094126381 (@172.16.0.238) 0.61ms referer=None
[W 2024-05-19 04:48:46.396 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 04:48:46.396 ServerApp] 403 GET /api/kernelspecs?1716094126389 (@172.16.0.238) 1.15ms referer=None
[W 2024-05-19 06:55:49.044 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.67ms referer=None
[I 2024-05-19 06:55:49.051 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.27ms
[W 2024-05-19 06:55:49.062 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 06:55:49.064 ServerApp] 403 GET /api/kernelspecs?1716101749054 (@172.16.0.238) 2.55ms referer=None
[W 2024-05-19 06:55:49.065 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 06:55:49.065 ServerApp] 403 GET /api/kernels?1716101749055 (@172.16.0.238) 0.74ms referer=None
[W 2024-05-19 06:55:49.066 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 06:55:49.066 ServerApp] 403 GET /api/kernels?1716101749057 (@172.16.0.238) 0.61ms referer=None
[W 2024-05-19 06:55:49.068 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 06:55:49.069 ServerApp] 403 GET /api/sessions?1716101749058 (@172.16.0.238) 0.70ms referer=None
[W 2024-05-19 06:55:49.077 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 06:55:49.077 ServerApp] 403 GET /api/kernelspecs?1716101749073 (@172.16.0.238) 0.59ms referer=None
[W 2024-05-19 07:10:05.790 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.36ms referer=None
[I 2024-05-19 07:10:05.857 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.33ms
[W 2024-05-19 07:10:05.889 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:10:05.891 ServerApp] 403 GET /api/kernelspecs?1716102605882 (@172.16.0.238) 2.21ms referer=None
[W 2024-05-19 07:10:05.891 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:10:05.892 ServerApp] 403 GET /api/kernels?1716102605883 (@172.16.0.238) 0.78ms referer=None
[W 2024-05-19 07:10:05.892 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:10:05.892 ServerApp] 403 GET /api/sessions?1716102605886 (@172.16.0.238) 1.15ms referer=None
[W 2024-05-19 07:10:05.893 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:10:05.893 ServerApp] 403 GET /api/kernels?1716102605885 (@172.16.0.238) 0.59ms referer=None
[W 2024-05-19 07:10:05.896 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:10:05.896 ServerApp] 403 GET /api/kernelspecs?1716102605893 (@172.16.0.238) 1.20ms referer=None
[W 2024-05-19 07:26:49.855 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.23ms referer=None
[I 2024-05-19 07:26:49.932 ServerApp] 302 GET / (@172.16.0.238) 0.45ms
[I 2024-05-19 07:26:49.948 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.57ms
[W 2024-05-19 07:26:50.092 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:26:50.094 ServerApp] 403 GET /api/kernelspecs?1716103610026 (@172.16.0.238) 1.90ms referer=None
[W 2024-05-19 07:26:50.094 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:26:50.095 ServerApp] 403 GET /api/kernels?1716103610028 (@172.16.0.238) 0.91ms referer=None
[W 2024-05-19 07:26:50.095 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:26:50.095 ServerApp] 403 GET /api/kernels?1716103610030 (@172.16.0.238) 1.27ms referer=None
[W 2024-05-19 07:26:50.096 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:26:50.096 ServerApp] 403 GET /api/sessions?1716103610031 (@172.16.0.238) 1.68ms referer=None
[W 2024-05-19 07:26:50.109 ServerApp] 404 GET /hub/api (@172.16.0.238) 1.22ms referer=None
[W 2024-05-19 07:26:50.110 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:26:50.110 ServerApp] 403 GET /api/kernelspecs?1716103610096 (@172.16.0.238) 0.78ms referer=None
[I 2024-05-19 07:26:50.164 ServerApp] 302 GET / (@172.16.0.238) 0.24ms
[I 2024-05-19 07:26:50.217 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.37ms
[W 2024-05-19 07:26:50.330 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:26:50.331 ServerApp] 403 GET /api/kernelspecs?1716103610303 (@172.16.0.238) 1.24ms referer=None
[W 2024-05-19 07:26:50.331 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:26:50.332 ServerApp] 403 GET /api/kernels?1716103610304 (@172.16.0.238) 0.68ms referer=None
[W 2024-05-19 07:26:50.332 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:26:50.333 ServerApp] 403 GET /api/kernels?1716103610306 (@172.16.0.238) 0.71ms referer=None
[W 2024-05-19 07:26:50.333 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:26:50.333 ServerApp] 403 GET /api/sessions?1716103610307 (@172.16.0.238) 1.11ms referer=None
[W 2024-05-19 07:26:50.341 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 07:26:50.342 ServerApp] 403 GET /api/kernelspecs?1716103610333 (@172.16.0.238) 0.81ms referer=None
[W 2024-05-19 08:21:55.804 ServerApp] 404 GET /hub/api (@172.16.0.238) 23.92ms referer=None
[I 2024-05-19 08:21:55.857 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.43ms
[W 2024-05-19 08:21:55.877 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 08:21:55.883 ServerApp] 403 GET /api/kernelspecs?1716106915861 (@172.16.0.238) 6.61ms referer=None
[W 2024-05-19 08:21:55.883 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 08:21:55.884 ServerApp] 403 GET /api/kernels?1716106915862 (@172.16.0.238) 7.32ms referer=None
[W 2024-05-19 08:21:55.884 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 08:21:55.885 ServerApp] 403 GET /api/kernels?1716106915865 (@172.16.0.238) 7.78ms referer=None
[W 2024-05-19 08:21:55.885 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 08:21:55.885 ServerApp] 403 GET /api/sessions?1716106915866 (@172.16.0.238) 8.22ms referer=None
[W 2024-05-19 09:27:46.825 ServerApp] 404 GET /hub/api (@127.0.0.1) 2.96ms referer=None
[I 2024-05-19 09:27:46.878 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.34ms
[W 2024-05-19 09:27:47.004 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 09:27:47.006 ServerApp] 403 GET /api/kernelspecs?1716110866956 (@127.0.0.1) 1.71ms referer=None
[W 2024-05-19 09:27:47.006 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 09:27:47.007 ServerApp] 403 GET /api/kernels?1716110866961 (@127.0.0.1) 0.62ms referer=None
[W 2024-05-19 09:27:47.007 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 09:27:47.007 ServerApp] 403 GET /api/kernels?1716110866965 (@127.0.0.1) 0.56ms referer=None
[W 2024-05-19 09:27:47.025 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 09:27:47.025 ServerApp] 403 GET /api/sessions?1716110866969 (@127.0.0.1) 0.70ms referer=None
[W 2024-05-19 09:27:47.082 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 09:27:47.083 ServerApp] 403 GET /api/kernelspecs?1716110867029 (@127.0.0.1) 0.72ms referer=None
[W 2024-05-19 12:34:03.253 ServerApp] 404 GET /hub/api (@127.0.0.1) 3.31ms referer=None
[I 2024-05-19 12:34:03.269 JupyterNotebookApp] 302 GET /tree? (@127.0.0.1) 0.36ms
[W 2024-05-19 12:34:03.304 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 12:34:03.306 ServerApp] 403 GET /api/kernelspecs?1716122043296 (@127.0.0.1) 2.33ms referer=None
[W 2024-05-19 12:34:03.306 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 12:34:03.306 ServerApp] 403 GET /api/kernels?1716122043299 (@127.0.0.1) 2.61ms referer=None
[W 2024-05-19 12:34:03.307 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 12:34:03.307 ServerApp] 403 GET /api/kernels?1716122043301 (@127.0.0.1) 2.92ms referer=None
[W 2024-05-19 12:34:03.307 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 12:34:03.307 ServerApp] 403 GET /api/sessions?1716122043302 (@127.0.0.1) 3.23ms referer=None
[W 2024-05-19 12:34:03.313 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 12:34:03.314 ServerApp] 403 GET /api/kernelspecs?1716122043307 (@127.0.0.1) 0.61ms referer=None
[W 2024-05-19 14:29:26.730 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.19ms referer=None
[I 2024-05-19 14:29:26.737 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.26ms
[W 2024-05-19 14:29:26.756 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:29:26.757 ServerApp] 403 GET /api/sessions?1716128966746 (@172.16.0.238) 2.25ms referer=None
[W 2024-05-19 14:29:26.758 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:29:26.758 ServerApp] 403 GET /api/kernelspecs?1716128966743 (@172.16.0.238) 0.89ms referer=None
[W 2024-05-19 14:29:26.758 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:29:26.759 ServerApp] 403 GET /api/kernels?1716128966744 (@172.16.0.238) 1.26ms referer=None
[W 2024-05-19 14:29:26.759 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:29:26.759 ServerApp] 403 GET /api/kernels?1716128966746 (@172.16.0.238) 1.62ms referer=None
[W 2024-05-19 14:32:30.179 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.27ms referer=None
[I 2024-05-19 14:32:30.257 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.56ms
[W 2024-05-19 14:32:30.311 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:32:30.312 ServerApp] 403 GET /api/kernelspecs?1716129150281 (@172.16.0.238) 2.18ms referer=None
[W 2024-05-19 14:32:30.312 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:32:30.313 ServerApp] 403 GET /api/kernels?1716129150284 (@172.16.0.238) 2.44ms referer=None
[W 2024-05-19 14:32:30.313 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:32:30.314 ServerApp] 403 GET /api/kernels?1716129150301 (@172.16.0.238) 0.71ms referer=None
[W 2024-05-19 14:32:30.314 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:32:30.314 ServerApp] 403 GET /api/sessions?1716129150304 (@172.16.0.238) 1.08ms referer=None
[W 2024-05-19 14:32:30.325 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:32:30.326 ServerApp] 403 GET /api/kernelspecs?1716129150314 (@172.16.0.238) 1.26ms referer=None
[W 2024-05-19 14:39:57.910 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.29ms referer=None
[I 2024-05-19 14:39:57.912 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.27ms
[W 2024-05-19 14:39:57.920 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:39:57.921 ServerApp] 403 GET /api/kernelspecs?1716129597914 (@172.16.0.238) 2.16ms referer=None
[W 2024-05-19 14:39:57.922 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:39:57.922 ServerApp] 403 GET /api/kernels?1716129597915 (@172.16.0.238) 1.00ms referer=None
[W 2024-05-19 14:39:57.922 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:39:57.923 ServerApp] 403 GET /api/kernels?1716129597917 (@172.16.0.238) 1.31ms referer=None
[W 2024-05-19 14:39:57.923 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:39:57.923 ServerApp] 403 GET /api/sessions?1716129597917 (@172.16.0.238) 1.63ms referer=None
[W 2024-05-19 14:39:57.930 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:39:57.930 ServerApp] 403 GET /api/kernelspecs?1716129597923 (@172.16.0.238) 1.25ms referer=None
[W 2024-05-19 14:40:07.152 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.50ms referer=None
[I 2024-05-19 14:40:07.315 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.70ms
[W 2024-05-19 14:40:07.361 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:40:07.362 ServerApp] 403 GET /api/kernelspecs?1716129607346 (@172.16.0.238) 2.01ms referer=None
[W 2024-05-19 14:40:07.363 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:40:07.363 ServerApp] 403 GET /api/kernels?1716129607347 (@172.16.0.238) 0.63ms referer=None
[W 2024-05-19 14:40:07.363 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:40:07.364 ServerApp] 403 GET /api/kernels?1716129607353 (@172.16.0.238) 0.69ms referer=None
[W 2024-05-19 14:40:07.364 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:40:07.364 ServerApp] 403 GET /api/sessions?1716129607355 (@172.16.0.238) 1.06ms referer=None
[W 2024-05-19 14:40:07.838 ServerApp] 404 GET /hub/api (@172.16.0.238) 1.05ms referer=None
[I 2024-05-19 14:40:07.895 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.39ms
[W 2024-05-19 14:40:07.922 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:40:07.923 ServerApp] 403 GET /api/kernelspecs?1716129607911 (@172.16.0.238) 1.23ms referer=None
[W 2024-05-19 14:40:07.923 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:40:07.924 ServerApp] 403 GET /api/kernels?1716129607912 (@172.16.0.238) 0.74ms referer=None
[W 2024-05-19 14:40:07.924 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:40:07.924 ServerApp] 403 GET /api/sessions?1716129607918 (@172.16.0.238) 1.10ms referer=None
[W 2024-05-19 14:40:07.924 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:40:07.925 ServerApp] 403 GET /api/kernels?1716129607917 (@172.16.0.238) 0.58ms referer=None
[W 2024-05-19 14:40:07.930 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 14:40:07.931 ServerApp] 403 GET /api/kernelspecs?1716129607926 (@172.16.0.238) 1.19ms referer=None
[W 2024-05-19 17:02:27.819 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.56ms referer=None
[I 2024-05-19 17:02:27.883 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.53ms
[W 2024-05-19 17:02:27.918 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 17:02:27.920 ServerApp] 403 GET /api/kernelspecs?1716138147899 (@172.16.0.238) 2.14ms referer=None
[W 2024-05-19 17:02:27.920 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 17:02:27.921 ServerApp] 403 GET /api/kernels?1716138147900 (@172.16.0.238) 0.69ms referer=None
[W 2024-05-19 17:02:27.921 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 17:02:27.922 ServerApp] 403 GET /api/kernels?1716138147905 (@172.16.0.238) 0.72ms referer=None
[W 2024-05-19 17:02:27.922 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 17:02:27.922 ServerApp] 403 GET /api/sessions?1716138147906 (@172.16.0.238) 1.09ms referer=None
[W 2024-05-19 17:02:39.092 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.33ms referer=None
[I 2024-05-19 17:02:39.169 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.56ms
[W 2024-05-19 17:02:39.220 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 17:02:39.221 ServerApp] 403 GET /api/kernelspecs?1716138159178 (@172.16.0.238) 1.80ms referer=None
[W 2024-05-19 17:02:39.221 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 17:02:39.222 ServerApp] 403 GET /api/kernels?1716138159180 (@172.16.0.238) 0.59ms referer=None
[W 2024-05-19 17:02:39.222 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 17:02:39.223 ServerApp] 403 GET /api/kernels?1716138159200 (@172.16.0.238) 0.68ms referer=None
[W 2024-05-19 17:02:39.223 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/data/tianyu_guo/miniconda3/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-05-19 17:02:39.223 ServerApp] 403 GET /api/sessions?1716138159201 (@172.16.0.238) 1.05ms referer=None
[W 2024-05-19 22:39:31.000 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.51ms referer=None
[I 2024-05-19 22:39:31.003 ServerApp] 302 GET / (@172.16.0.238) 0.48ms
[I 2024-05-19 22:39:31.009 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.43ms
[W 2024-05-19 22:39:32.748 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.57ms referer=None
[I 2024-05-19 22:39:32.751 ServerApp] 302 GET / (@172.16.0.238) 0.44ms
[I 2024-05-19 22:39:32.753 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.46ms
[W 2024-05-19 22:39:44.586 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.54ms referer=None
[I 2024-05-19 22:39:44.588 ServerApp] 302 GET / (@172.16.0.238) 0.22ms
[I 2024-05-19 22:39:44.594 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.35ms
[I 2024-05-19 22:39:44.676 ServerApp] Kernel started: d7befb60-9f66-4daa-8471-c4cb45e1f06d
[I 2024-05-19 22:39:45.919 ServerApp] Connecting to kernel d7befb60-9f66-4daa-8471-c4cb45e1f06d.
[I 2024-05-20 01:40:25.680 ServerApp] Kernel restarted: d7befb60-9f66-4daa-8471-c4cb45e1f06d
[I 2024-05-20 01:40:25.683 ServerApp] Starting buffering for d7befb60-9f66-4daa-8471-c4cb45e1f06d:525d1069-e4ea-4722-a71c-02f74ad86e0b
[I 2024-05-20 01:40:25.690 ServerApp] Connecting to kernel d7befb60-9f66-4daa-8471-c4cb45e1f06d.
[I 2024-05-20 01:40:25.690 ServerApp] Restoring connection for d7befb60-9f66-4daa-8471-c4cb45e1f06d:525d1069-e4ea-4722-a71c-02f74ad86e0b
[W 2024-05-20 02:51:56.163 ServerApp] 404 GET /hub/api (@172.16.0.238) 4.95ms referer=None
[I 2024-05-20 02:51:56.165 ServerApp] 302 GET / (@172.16.0.238) 0.23ms
[I 2024-05-20 02:51:56.173 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.30ms
[I 2024-05-20 02:51:56.294 ServerApp] Kernel started: 988314a5-a6fa-43a2-99e8-4af7e34c34cf
[I 2024-05-20 02:52:01.874 ServerApp] Connecting to kernel 988314a5-a6fa-43a2-99e8-4af7e34c34cf.
[W 2024-05-20 04:51:27.790 ServerApp] 404 GET /hub/api (@172.16.0.238) 43.81ms referer=None
[I 2024-05-20 04:51:27.796 ServerApp] 302 GET / (@172.16.0.238) 0.26ms
[I 2024-05-20 04:51:27.810 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.58ms
[W 2024-05-20 04:51:29.288 ServerApp] 404 GET /hub/api (@172.16.0.238) 21.56ms referer=None
[W 2024-05-20 04:51:29.289 ServerApp] 404 GET /hub/api (@172.16.0.238) 22.18ms referer=None
[I 2024-05-20 04:51:29.292 ServerApp] 302 GET / (@172.16.0.238) 0.19ms
[I 2024-05-20 04:51:29.293 ServerApp] 302 GET / (@172.16.0.238) 0.17ms
[I 2024-05-20 04:51:29.297 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.43ms
[I 2024-05-20 04:51:29.298 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.72ms
[W 2024-05-20 04:51:34.231 ServerApp] 404 GET /hub/api (@172.16.0.238) 14.34ms referer=None
[I 2024-05-20 04:51:34.234 ServerApp] 302 GET / (@172.16.0.238) 0.35ms
[I 2024-05-20 04:51:34.239 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.37ms
[I 2024-05-20 04:51:34.390 ServerApp] Kernel started: e39fbd32-7183-4796-8991-e8d1fb52d814
[I 2024-05-20 04:51:39.843 ServerApp] Connecting to kernel e39fbd32-7183-4796-8991-e8d1fb52d814.
[I 2024-05-20 08:21:01.271 ServerApp] Kernel restarted: e39fbd32-7183-4796-8991-e8d1fb52d814
[I 2024-05-20 08:21:01.281 ServerApp] Starting buffering for e39fbd32-7183-4796-8991-e8d1fb52d814:1f638bf4-1b4c-46b0-a1b7-843602a54615
[I 2024-05-20 08:21:01.287 ServerApp] Connecting to kernel e39fbd32-7183-4796-8991-e8d1fb52d814.
[I 2024-05-20 08:21:01.293 ServerApp] Restoring connection for e39fbd32-7183-4796-8991-e8d1fb52d814:1f638bf4-1b4c-46b0-a1b7-843602a54615
[W 2024-05-20 08:21:04.170 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7effd50d6c30>
[I 2024-05-20 08:30:05.013 ServerApp] Kernel interrupted: e39fbd32-7183-4796-8991-e8d1fb52d814
[I 2024-05-20 12:04:18.157 ServerApp] Starting buffering for d7befb60-9f66-4daa-8471-c4cb45e1f06d:525d1069-e4ea-4722-a71c-02f74ad86e0b
[I 2024-05-20 12:04:18.185 ServerApp] Starting buffering for 988314a5-a6fa-43a2-99e8-4af7e34c34cf:fe2956d1-30ff-4273-a67f-c369b8eb2e88
[I 2024-05-20 14:04:58.264 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2024-05-20 14:04:58.264 ServerApp] kernel e39fbd32-7183-4796-8991-e8d1fb52d814 restarted
[I 2024-05-20 14:04:58.303 ServerApp] Starting buffering for e39fbd32-7183-4796-8991-e8d1fb52d814:1f638bf4-1b4c-46b0-a1b7-843602a54615
[I 2024-05-20 14:04:58.402 ServerApp] Connecting to kernel e39fbd32-7183-4796-8991-e8d1fb52d814.
[I 2024-05-20 14:04:58.403 ServerApp] Restoring connection for e39fbd32-7183-4796-8991-e8d1fb52d814:1f638bf4-1b4c-46b0-a1b7-843602a54615
[W 2024-05-20 17:08:25.671 ServerApp] 404 GET /hub/api (@172.16.0.238) 44.71ms referer=None
[W 2024-05-20 17:08:25.673 ServerApp] 404 GET /hub/api (@172.16.0.238) 0.75ms referer=None
[I 2024-05-20 17:08:26.211 ServerApp] 302 GET / (@172.16.0.238) 3.61ms
[I 2024-05-20 17:08:26.212 ServerApp] 302 GET / (@172.16.0.238) 0.23ms
[I 2024-05-20 17:08:26.269 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 4.31ms
[I 2024-05-20 17:08:26.270 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.25ms
[W 2024-05-20 17:08:26.631 ServerApp] 404 GET /hub/api (@172.16.0.238) 0.69ms referer=None
[I 2024-05-20 17:08:26.633 ServerApp] 302 GET / (@172.16.0.238) 0.20ms
[I 2024-05-20 17:08:26.637 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.25ms
[I 2024-05-20 17:08:26.673 ServerApp] Connecting to kernel 988314a5-a6fa-43a2-99e8-4af7e34c34cf.
[W 2024-05-20 17:08:29.428 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@172.16.0.238) 2.92ms referer=None
[W 2024-05-20 17:08:29.428 ServerApp] 404 GET /nbextensions/viewer/extension.js (@172.16.0.238) 3.23ms referer=None
[W 2024-05-20 17:08:29.429 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.55ms referer=None
[W 2024-05-20 17:08:29.429 ServerApp] 404 GET /hub/api (@172.16.0.238) 3.85ms referer=None
[I 2024-05-20 17:08:29.432 ServerApp] 302 GET / (@172.16.0.238) 0.19ms
[I 2024-05-20 17:08:29.434 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.28ms
[W 2024-05-20 17:08:29.441 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@172.16.0.238) 0.74ms referer=None
[W 2024-05-20 17:08:29.442 ServerApp] 404 GET /nbextensions/viewer/extension.js (@172.16.0.238) 1.03ms referer=None
[W 2024-05-20 17:08:30.505 ServerApp] 404 GET /hub/api (@172.16.0.238) 2.89ms referer=None
[I 2024-05-20 17:08:30.507 ServerApp] 302 GET / (@172.16.0.238) 0.21ms
[I 2024-05-20 17:08:30.510 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.27ms
[I 2024-05-20 17:08:30.555 ServerApp] Connecting to kernel d7befb60-9f66-4daa-8471-c4cb45e1f06d.
[W 2024-05-20 17:08:31.395 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@172.16.0.238) 1.45ms referer=None
[W 2024-05-20 17:08:31.395 ServerApp] 404 GET /hub/api (@172.16.0.238) 1.62ms referer=None
[W 2024-05-20 17:08:31.396 ServerApp] 404 GET /nbextensions/viewer/extension.js (@172.16.0.238) 1.87ms referer=None
[W 2024-05-20 17:08:31.396 ServerApp] 404 GET /hub/api (@172.16.0.238) 2.14ms referer=None
[I 2024-05-20 17:08:31.398 ServerApp] 302 GET / (@172.16.0.238) 0.36ms
[I 2024-05-20 17:08:31.401 JupyterNotebookApp] 302 GET /tree? (@172.16.0.238) 0.50ms
[W 2024-05-20 17:08:31.409 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@172.16.0.238) 0.89ms referer=None
[W 2024-05-20 17:08:31.410 ServerApp] 404 GET /nbextensions/viewer/extension.js (@172.16.0.238) 1.13ms referer=None
